name: litres_mobile
description: "Litres mobile app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^6.1.5
  flutter_signin_button: ^2.0.0
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  dotted_border: ^2.1.0
  font_awesome_flutter: ^9.2.0
  graphql_flutter: ^5.2.0
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/